# Generated by Django 4.0.1 on 2022-01-18 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblockitemtranslation',
            name='name',
            field=models.CharField(max_length=700, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='categorytranslation',
            name='additional',
            field=models.CharField(blank=True, max_length=500, verbose_name='Additional'),
        ),
    ]
