# Generated by Django 4.0.1 on 2022-01-18 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_addblockitemtranslation_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addblockitemtranslation',
            name='name',
            field=models.CharField(blank=True, max_length=1700, verbose_name='Name'),
        ),
    ]
