# Generated by Django 4.0.1 on 2022-01-30 22:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_product_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work', models.CharField(blank=True, max_length=400, verbose_name='Work')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('url', models.URLField(blank=True, verbose_name='URL')),
            ],
        ),
    ]
