# Generated by Django 4.0.1 on 2022-01-31 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='producttranslation',
            name='image',
            field=models.ImageField(blank=True, upload_to='product_images/', verbose_name='Image'),
        ),
    ]
