# Generated by Django 4.0.2 on 2022-02-08 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_alter_categoryimage_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producttranslation',
            name='price',
            field=models.CharField(blank=True, max_length=100, verbose_name='price'),
        ),
    ]
