# Generated by Django 4.0.2 on 2022-02-09 18:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_producttranslation_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='corrugated',
            field=models.BooleanField(blank=True, default=False, verbose_name='Korobka '),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length', models.CharField(blank=True, max_length=200, verbose_name='Length')),
                ('height', models.CharField(blank=True, max_length=200, verbose_name='Height')),
                ('width', models.CharField(blank=True, max_length=200, verbose_name='width')),
                ('amount', models.PositiveIntegerField(verbose_name='Amount')),
                ('name', models.CharField(max_length=200, verbose_name='Name')),
                ('phone_number', models.CharField(max_length=15, verbose_name='Phone')),
                ('email', models.EmailField(blank=True, max_length=200, verbose_name='Email')),
                ('message', models.TextField(verbose_name='Text')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='main.product')),
            ],
        ),
    ]
