# Generated by Django 4.0.2 on 2022-02-10 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_alter_order_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
    ]
