# Generated by Django 4.0.2 on 2022-02-10 22:09

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_alter_order_options_order_additonal_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdditionalFormValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='main.product')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.CreateModel(
            name='AdditionalFormValueTranslation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('name', models.CharField(blank=True, max_length=200, verbose_name='Name')),
                ('type', models.CharField(blank=True, choices=[('TEXT', 'text'), ('NUMBER', 'number')], max_length=20, verbose_name='Type')),
                ('placeholder', models.CharField(blank=True, max_length=300, verbose_name='Placeholder')),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='main.additionalformvalue')),
            ],
            options={
                'verbose_name': 'additional form value Translation',
                'db_table': 'main_additionalformvalue_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
