# Generated by Django 4.0.2 on 2022-02-10 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_additionalformvalue_additionalformvaluetranslation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='additionalformvaluetranslation',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'TEXT'), ('number', 'NUMBER')], max_length=20, verbose_name='Type'),
        ),
    ]
