# Generated by Django 4.0.2 on 2022-02-11 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_clientmessage_date_order_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalformvaluetranslation',
            name='type',
        ),
        migrations.RemoveField(
            model_name='additionalformvalue',
            name='product',
        ),
        migrations.AddField(
            model_name='additionalformvalue',
            name='product',
            field=models.ManyToManyField(blank=True, related_name='form_input', to='main.Product'),
        ),
    ]
