# Generated by Django 4.0.2 on 2022-02-11 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_remove_additionalformvaluetranslation_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='additionalformvaluetranslation',
            name='type',
            field=models.CharField(blank=True, choices=[('text', 'TEXT'), ('number', 'NUMBER')], max_length=20, verbose_name='Type'),
        ),
    ]
