# Generated by Django 4.0.2 on 2022-02-11 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_additionalformvaluetranslation_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='height',
        ),
        migrations.RemoveField(
            model_name='order',
            name='length',
        ),
        migrations.RemoveField(
            model_name='order',
            name='width',
        ),
    ]
