# Generated by Django 4.0.2 on 2022-02-11 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0022_remove_order_height_remove_order_length_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='phone',
            field=models.CharField(default=1, max_length=200, verbose_name='Phone Number'),
            preserve_default=False,
        ),
    ]
