# Generated by Django 4.0.2 on 2022-02-11 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0023_order_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='additonal_info',
            new_name='additional_info',
        ),
    ]
