# Generated by Django 4.0.2 on 2022-02-11 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_rename_additonal_info_order_additional_info'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoryimage',
            options={'verbose_name': 'Category Image', 'verbose_name_plural': 'Category Images'},
        ),
        migrations.AlterModelOptions(
            name='categoryimagetranslation',
            options={'default_permissions': (), 'managed': True, 'verbose_name': 'Category Image Translation'},
        ),
        migrations.AlterModelOptions(
            name='clientmessage',
            options={'verbose_name': 'Client Message', 'verbose_name_plural': 'Client Messages'},
        ),
    ]
