# Generated by Django 4.0.2 on 2022-02-11 22:32

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_alter_categoryimage_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientmessage',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Email'),
        ),
        migrations.AddField(
            model_name='clientmessage',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name='Name'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='clientmessage',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Phone'),
        ),
    ]
